import "./globals.css";
import Navigation from "./components/Navigation/Navigation";
import { Quicksand} from "next/font/google";
import Footer from "./components/Footer";
import { WebVitals } from "./components/web-vitals";
export const quicksand = Quicksand({
  weight: ["300","400","500","600", "700",],
  style: ["normal"],
  subsets: ["latin"],
  display: "block",
});

export const metadata = {
  title: "AB-Designer",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html>
      <body className={`${quicksand.className} select-none bg-main overflow-x-hidden`}>
        <main className="min-h-screen flex-col flex gap-14 p-5 lg:flex-row lg:pt-16 lg:pl-20">
          <Navigation />
          <WebVitals/>
          {children}
        </main>
          <Footer font={quicksand}/>
      </body>
    </html>
  );
}
