import "./globals.css";
import Navigation from "./components/Navigation";
import { Quicksand, Racing_Sans_One} from "next/font/google";
import Head from "next/head";
import Footer from "./components/Footer";
// export const alumni = Alumni_Sans_Pinstripe({
//   weight: ["400"],
//   style: ["normal"],
//   subsets: ["latin"],
// display: "block", //? WHAT DOES THIS DO?
// });
export const quicksand = Quicksand({
  weight: ["300","400","500","600", "700",],
  style: ["normal"],
  subsets: ["latin"],
  // display: "block", //? WHAT DOES THIS DO?
});

export const metadata = {
  title: "Abd-Albaset Architect",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
      <meta name="theme-color" content="#4285f4" />
      </Head>
      <body className={quicksand.className}>
        <main className="min-h-screen flex-col flex gap-14 p-5 lg:flex-row lg:pt-16 lg:pl-20">
          <Navigation />
          {children}
        </main>
          <Footer font={quicksand}/>
      </body>
    </html>
  );
}
